- name: Un playbook muy muy sencillo
  # A quienes se les va a operar 
  hosts: web
  become: true
  tasks:
    - name: Dame un mensaje
      ansible.builtin.debug:
        msg: "Bienvenido al mundo de Ansible"
    - name: Upgrade all packages
      ansible.builtin.yum:
        name: '*'
        state: latest
      register: salida_dnf
    - name: reboot si hubo actualizacion
      ansible.builtin.reboot: 
      when: salida_dnf is changed

    - name: Enviar mensaje a Slack
      community.general.slack:
        token: "xoxb-7935070466084-7932628298002-SSBBdDRntxMJreIMU08tcbfJ"
        msg: "¡Despliegue completado con éxito!"
        channel: "#anible"

      
